# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: groubaud <groubaud@student.s19.be >        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/09 17:30:45 by groubaud          #+#    #+#              #
#    Updated: 2022/07/09 17:30:45 by groubaud         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	philo

SRCS	=	philosophers
INCLUDE	=	philo.h

CC		=	gcc
FLAGS	=	-Wall -Wextra -All

all	:	$(NAME)

$(NAME) :	$(INCLUDE)